version: '2'
services:
    e2r-app:
        image: e2r
        external_links:
            - e2r-mariadb:mariadb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/e2r
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    e2r-mariadb:
        extends:
            file: mariadb.yml
            service: e2r-mariadb
